<script type="text/javascript" charset="utf-8">
	$(document).ready(function(){
		$('.kint-trace a').click(function(){
			return false;
		})
		var trigger = $('.show_trace');
		var hide_text = 'Hide The Trace';
		var text = 'Show The Trace';
		var trace = $('.kint-trace');
		trigger.click(function(){
		
			if(trace.is(':visible') == false) {
				trigger.text(hide_text);
				trace.slideDown()	
			}else{
				trigger.text(text);
				trace.slideUp()
			}
			
		});
	})
</script>

<br class="clear"/>
<div class="right mb10	">
	<span class="button show_trace">Show The Trace</span>

</div>

<div class="clear"></div>

<div class="kint-trace hide">
	<ol>
		<?php foreach ( $output as $i => $step ): ?>
		<li>
			<p>
				<?php if ( $step['file'] ): ?>
				<a href="#" class="kint-source-parent"><?php echo call_user_func( self::$pathDisplayCallback, $step['file'], $step['line'] )?></a>
				<?php else: ?>
				PHP internal call
				<?php endif ?>
				&raquo;
				<?php echo $step['function']?>(<?php if ( $step['args'] ): ?><a href="#" class="kint-args-parent">arguments</a><?php endif ?>)
			</p>
			<?php if ( $step['args'] ): ?>
			<div class="kint-args">
				<table cellspacing="0">
					<?php foreach ( $step['args'] as $name => $arg ): ?>
					<tr>
						<td><code><?php echo $name ?></code></td>
						<td>
							<pre><?php s( $arg ) ?></pre>
						</td>
					</tr>
					<?php endforeach ?>
				</table>
			</div>
			<?php endif ?>
			<?php if ( $step['file'] ): ?>
			<div class="kint-source"><?php echo $step['source'] ?></div>
			<?php endif ?>
		</li>
		<?php endforeach ?>
	</ol>
	<? +d(get_defined_vars())?>
</div>

